# Generated by Django 5.0.12 on 2025-06-12 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('Code', models.CharField(db_column='Code', max_length=6, primary_key=True, serialize=False, verbose_name='کد')),
                ('Title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('AppLabel', models.SlugField(blank=True, max_length=100, null=True, verbose_name='نام لاتین برنامه')),
            ],
            options={
                'verbose_name': 'برنامه',
                'verbose_name_plural': 'برنامه ها',
            },
        ),
        migrations.CreateModel(
            name='PermissionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100, verbose_name='شرح')),
            ],
            options={
                'verbose_name': 'گروه دسترسی',
                'verbose_name_plural': 'گروه های دسترسی ',
            },
        ),
        migrations.CreateModel(
            name='PermissionVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(max_length=5, verbose_name='کد')),
                ('Title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('VariableDescription', models.CharField(max_length=200, verbose_name='شرح')),
            ],
            options={
                'verbose_name': 'متغیر',
                'verbose_name_plural': 'متغیر ها',
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IPAddress', models.GenericIPAddressField(verbose_name='ادرس')),
                ('DNSName', models.CharField(blank=True, max_length=200, null=True, verbose_name='نام سرور')),
                ('ServerName', models.CharField(max_length=200, verbose_name='نام ')),
            ],
            options={
                'verbose_name': 'سرور',
                'verbose_name_plural': 'سرورها',
            },
        ),
        migrations.CreateModel(
            name='AppPermissionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PermissionType', models.CharField(max_length=100)),
                ('AppCode', models.ForeignKey(db_column='AppCode', on_delete=django.db.models.deletion.CASCADE, to='AccessControl.app', verbose_name='کد برنامه')),
            ],
            options={
                'verbose_name': 'نوع دسترسی',
                'verbose_name_plural': 'نوع های دسترسی ',
            },
        ),
        migrations.CreateModel(
            name='AppTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TeamCode', models.CharField(max_length=3)),
                ('AppCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AccessControl.app', verbose_name='نام برنامه')),
            ],
            options={
                'verbose_name': 'تیم برنامه ',
                'verbose_name_plural': 'تیم های برنامه ها ',
            },
        ),
        migrations.CreateModel(
            name='AppURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('URL', models.CharField(max_length=500, verbose_name='مسیر دسترسی')),
                ('IsPublic', models.BooleanField(default=False)),
                ('AppCode', models.ForeignKey(db_column='AppCode', on_delete=django.db.models.deletion.CASCADE, to='AccessControl.app', verbose_name='کد اپلیکیشن')),
            ],
            options={
                'verbose_name': 'آدرس',
                'verbose_name_plural': 'آدرس ها',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('Code', models.CharField(db_column='Code', max_length=10, primary_key=True, serialize=False, verbose_name='کد')),
                ('Title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('PermissionType', models.CharField(choices=[('V', 'مجوز مشاهده'), ('E', 'مجوز ویرایش'), ('A', 'دسترسی کامل'), ('U', 'دسترسی ادرس'), ('D', 'دسترسی پورتال')], max_length=1, verbose_name='نوع مجوز')),
                ('AppCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AccessControl.app', verbose_name='کد برنامه')),
            ],
            options={
                'verbose_name': '  دسترسی ',
                'verbose_name_plural': 'دسترسی ها ',
            },
        ),
        migrations.CreateModel(
            name='GroupUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User', models.CharField(max_length=50)),
                ('Group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AccessControl.permissiongroup', verbose_name='گروه')),
            ],
            options={
                'verbose_name': 'گروه کاربری ',
                'verbose_name_plural': 'گروه های کاربری ',
            },
        ),
        migrations.CreateModel(
            name='PermissionVariableValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OwnerVariableRole', models.IntegerField(blank=True, null=True, verbose_name='سمت')),
                ('OwnerVariableUser', models.CharField(blank=True, max_length=150, null=True, verbose_name='کاربر')),
                ('App', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AccessControl.app', verbose_name='نام برنامه')),
                ('OwnerVariableGroup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AccessControl.permissiongroup', verbose_name='گروه')),
                ('PermissionVariable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AccessControl.permissionvariable', verbose_name='نام تغیر')),
            ],
            options={
                'verbose_name': 'مقدار متغیر',
                'verbose_name_plural': 'مقادیر متغیرها',
            },
        ),
        migrations.CreateModel(
            name='RelatedPermissionAPPURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AppURL', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AccessControl.appurl', verbose_name='آدرس')),
                ('Permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AccessControl.permission', verbose_name='نام دسترسی')),
            ],
            options={
                'verbose_name': 'ارتباط آدرس با دسترسی ',
                'verbose_name_plural': 'آدرس ها و دسترسی های مرتبط ',
            },
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('Code', models.CharField(db_column='Code', max_length=3, primary_key=True, serialize=False, verbose_name='کد')),
                ('Title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('PortNumber', models.IntegerField(verbose_name='پورت')),
                ('Logo', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='تصویر')),
                ('Server', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AccessControl.server', verbose_name='نام سرور')),
            ],
            options={
                'verbose_name': 'سیستم',
                'verbose_name_plural': 'سیستم ها',
            },
        ),
        migrations.AddField(
            model_name='app',
            name='SystemCode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AccessControl.system', verbose_name='کدسیستم'),
        ),
        migrations.CreateModel(
            name='UserRoleGroupPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OwnerPermissionRole', models.IntegerField(blank=True, null=True)),
                ('OwnerPermissionUser', models.CharField(blank=True, max_length=50, null=True)),
                ('OwnerPermissionGroup', models.ForeignKey(blank=True, db_column='OwnerPermissionGroup', null=True, on_delete=django.db.models.deletion.CASCADE, to='AccessControl.permissiongroup', verbose_name='گروه')),
                ('PermissionCode', models.ForeignKey(db_column='PermissionCode', on_delete=django.db.models.deletion.CASCADE, to='AccessControl.permission', verbose_name='کددسترسی')),
            ],
            options={
                'verbose_name': 'دسته بندی دسترسی ',
                'verbose_name_plural': 'دسته بندی دسترسی ها ',
            },
        ),
        migrations.CreateModel(
            name='VariableValueRelated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ValueTitle', models.CharField(max_length=200, verbose_name='مقدار متغیر')),
                ('VariableValue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AccessControl.permissionvariablevalue', verbose_name=' متغیر')),
            ],
            options={
                'verbose_name': 'مقدار ',
                'verbose_name_plural': 'مقادیر ',
            },
        ),
    ]
