# Generated by Django 5.0.12 on 2025-06-14 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AppName', models.CharField(max_length=200, verbose_name='نام لاتین برنامه')),
                ('AppTitle', models.CharField(max_length=200, verbose_name='عنوان برنامه')),
                ('ENGINE', models.CharField(blank=True, max_length=200, null=True)),
                ('NAME', models.CharField(blank=True, max_length=200, null=True)),
                ('USER', models.CharField(blank=True, max_length=200, null=True)),
                ('PASSWORD', models.CharField(blank=True, max_length=200, null=True)),
                ('HOST', models.CharField(blank=True, max_length=200, null=True)),
                ('PORT', models.CharField(blank=True, max_length=200, null=True)),
                ('OPTIONS', models.JSONField(blank=True, null=True)),
                ('APPIP', models.GenericIPAddressField(blank=True, null=True, verbose_name='آیپی سرور برنامه')),
                ('APPPORT', models.IntegerField(blank=True, null=True, verbose_name='پورت سرور برنامه')),
                ('APPSCHEMA', models.CharField(blank=True, default='http://', max_length=10, verbose_name='اس اس ال برنامه')),
            ],
            options={
                'verbose_name': 'اطلاعات برنامه',
                'verbose_name_plural': 'اطلاعات برنامه ها',
            },
        ),
        migrations.CreateModel(
            name='PermissionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'مجوز گروه',
                'verbose_name_plural': 'دسترسی گروه ها',
            },
        ),
        migrations.CreateModel(
            name='PermissionUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'مجوز کاربر',
                'verbose_name_plural': 'دسترسی کاربران',
            },
        ),
        migrations.CreateModel(
            name='UpdateAppInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'بروزرسانی',
                'verbose_name_plural': 'بروزرسانی اطلاعات برنامه ها',
            },
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'گروه کاربر',
                'verbose_name_plural': 'اعضای گروه ها',
            },
        ),
    ]
